### ISSUE TITLE
[PE-D][Tester D] Price of "0.00"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113T-T09-3/tp#122]
The price does not display if it is "0.00". However, the user could want to display the price as zero, just for their knowledge and so it would be an inconvenience is it was just marked as an X instead. 

![image (6).png](https://raw.githubusercontent.com/kirangeofran/ped/main/files/881da177-5362-4c3c-bf1e-bf8d2c75b237.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kirangeofran/ped#5

**Comment by NgYaoDong** [comment]
Written in UG that [X] will be displayed when entering 0.00 as PRICE
